services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - Inception

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - Inception
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - Inception

  adminer:
    build: requirements/bonus/adminer/
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    networks:
      - Inception
  redis:
    build: requirements/bonus/redis/
    container_name: redis
    restart: always
    depends_on:
      - mariadb
    networks:
      - Inception
  ftp:
    build: requirements/bonus/ftp/
    container_name: ftp
    ports:
      - "21:21"
      - "10000-11000:10000-11000"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    env_file: .env
    depends_on:
        - wordpress
    networks:
      - Inception
  sttic_site:
    build: requirements/bonus/static/
    container_name: static_site
    restart: always
    depends_on:
      - nginx
    networks:
      - Inception
  portainer:
    build: requirements/bonus/portainer/
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - Inception

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o : bind
      device: /home/${USER}/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
networks:
  Inception:
