services:
  nginx:
    build: requirements/nginx/
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  mariadb:
    build: requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  adminer:
    build: requirements/bonus/adminer/
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception

  redis:
    build: requirements/bonus/redis/
    image: redis
    container_name: redis
    restart: always
    networks:
      - inception

  ftp:
    build: requirements/bonus/ftp/
    image: ftp
    container_name: ftp
    ports:
      - "21:21"
      - "10000-10010:10000-10010"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    env_file: .env
    depends_on:
        - wordpress
    networks:
      - inception

  static_site:
    build: requirements/bonus/static/
    image: static_site    
    container_name: static_site
    restart: always
    depends_on:
      - nginx
    networks:
      - inception

  portainer:
    build: requirements/bonus/portainer/
    image: portainer
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inception

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

networks:
  inception:
    name: inception
