events{}

http{
	server{
		listen 80;
		server_name hfakou.42.fr;
		root /var/www/html/; # Path to WordPress core files
		index index.php index.html;
		location / {
			try_files $uri $uri/ =404;
		}
		
	}
}

