services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - Inception

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - Inception

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - Inception

volumes:
  wordpress_data:
  mariadb_data:

networks:
  Inception:
